import Gallery from "@/components/layout/Gallery";
import Header from "@/components/layout/Header";
import Main from "@/components/layout/Main";
import { NextUIProvider } from "@nextui-org/react";
import "lightgallery/css/lg-thumbnail.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lightgallery.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const images = [
  {
    src: "https://pic.netbian.com/uploads/allimg/241023/234955-17296985953e14.jpg",
    alt: "ces ",
  },
  {
    src: "https://pic.netbian.com/uploads/allimg/241023/231835-1729696715f4d7.jpg",
    alt: "ces",
  },
  {
    src: "https://pic.netbian.com/uploads/allimg/241020/235248-1729439568e63d.jpg",
    alt: "ces",
  },
  {
    src: "https://pic.netbian.com/uploads/allimg/241014/171403-1728897243c203.jpg",
    alt: "ces",
  },
  {
    src: "https://pic.netbian.com/uploads/allimg/240514/004624-1715618784f9c9.jpg",
    alt: "ces",
  },
  {
    src: "https://pic.netbian.com/uploads/allimg/240521/233805-17163058853baa.jpg",
    alt: "ces",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUIProvider>
          <Header />
          <Main>
            <Gallery images={images} />
          </Main>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
